version: '3'
services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - /tmp/app:/var/log/app
    ports:
      - "3080:3080"
    depends_on:
      - postgres
      - redis
    command: ["./wait-for-it.sh", "db:5432"]

  postgres:
    image: "postgres:12"
    restart: always
    container_name: "go8_postgres"
    environment:
      - POSTGRES_USER=go8_user
      - POSTGRES_PASSWORD=somelongrandomstring!
      - POSTGRES_DB=go8_db
    ports:
      - "5432:5432"
    volumes:
      - postgres12go8db:/var/lib/postgresql/data

  redis:
    image: redis:5
    restart: always
    container_name: rediscache
    expose:
      - 6379
    ports:
      - '6379:6379'

  elasticsearch:
    image: elasticsearch:7.9.1
    container_name: elasticsearch7
    environment:
#      - cluster.initial_master_nodes=es01
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

volumes:
  postgres12go8db:
  elasticsearch-data: