version: '3.4'

services:

  server:
    image: go8
    container_name: "go8container"
    build: ./
    command: ./app
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - postgres
    environment:
      - WAIT_HOSTS: postgres:${DB_PORT}

  postgres:
    image: "postgres:13"
    restart: always
    container_name: "go8_postgres"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres13go8db:/var/lib/postgresql/data

volumes:
  postgres13go8db: