version: '3'
services:
  postgres:
    image: "postgres:13"
    restart: always
    container_name: "go8_postgres"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres13go8db:/var/lib/postgresql/data

  redis:
    image: redis:5
    restart: always
    container_name: rediscache
    expose:
      - 6379
    ports:
      - '6379:6379'

volumes:
  postgres13go8db: