version: '3.4'

services:

  server:
    image: "go8/server"
    container_name: "go8_container"
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["/home/appuser/app/server"]
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - postgres

  postgres:
    image: "postgres:13"
    restart: "no"
    container_name: "go8_postgres"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - postgres13go8db:/var/lib/postgresql/data

volumes:
  postgres13go8db:
