version: '3.4'

services:

  server:
    image: "go8/server_test"
    container_name: "go8_container_test"
    env_file:
      - .env
    build:
      context: ../
      dockerfile: ./docker-test/Dockerfile
    entrypoint: ["/home/appuser/app/server"]
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - postgres
#    network_mode: "host"

  postgres:
    image: "postgres:13"
    restart: "no"
    container_name: "go8_postgres_e2e"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5434:5432
#    expose:
#      - 5434
    volumes:
    - go8_dockertest

volumes:
  go8_dockertest: {}